webapp/news/models.py
from webapp.db import db

class News(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String, nullable=False)
	url = db.Column(db.String, unique=True, nullable=False)
	published = db.Column(db.DateTime, nullable=False)
	text = db.Column(db.Text, nullable=True)

	def __repr__(self):
		return '<News {} {}>'.format(self.title, self.url)

webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.db import db

class User(db.Model, UserMixin):
	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(50), index=True, unique=True)
	password = db.Column(db.String(128))
	role = db.Column(db.String(10), index=True)
	email = db.Column(db.String(50))
	
	def set_password(self, password):
		self.password = generate_password_hash(password)

	def check_password(self, password):
		return check_password_hash(self.password, password)

	@property
	def is_admin(self):
		return self.role == 'admin'
	

	def __repr__(self):
		return "<User name={} id={}>".format(self.username, self.id)

webapp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
	username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
	password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
	submit = SubmitField('Отправить', render_kw={"class": "btn btn-primary"})
		

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import  BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo

class LoginForm(FlaskForm):
	username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
	password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
	remember_me = BooleanField('Запомнить меня', default=True, render_kw={"class": "form-check-input"})
	submit = SubmitField('Отправить', render_kw={"class": "btn btn-primary"})
		
class RegistrationForm(FlaskForm):
	username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
	email = StringField('Электронная почта', validators=[DataRequired(), Email()], render_kw={"class": "form-control"})
	password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
	password2 = PasswordField('Повторите пароль', validators=[DataRequired(), EqualTo('password')], render_kw={"class": "form-control"})
	submit = SubmitField('Отправить', render_kw={"class": "btn btn-primary"})
		

webapp/__init__.py
from flask import Flask, flash, render_template, redirect, url_for
from flask_login import LoginManager, current_user, login_required
from flask_migrate import Migrate

from webapp.db import db
from webapp.admin.views import blueprint as admin_blueprint
from webapp.news.views import blueprint as news_blueprint
from webapp.user.models import User
from webapp.user.views import blueprint as user_blueprint
from webapp.weather import weather_by_city

def create_app():	
	app = Flask(__name__)
	app.config.from_pyfile("config.py")
	db.init_app(app)
	migrate = Migrate(app, db)

	login_manager = LoginManager()
	login_manager.init_app(app)
	login_manager.login_view = 'user.login'
	app.register_blueprint(admin_blueprint)
	app.register_blueprint(news_blueprint)
	app.register_blueprint(user_blueprint)
	

	@login_manager.user_loader
	def load_user(user_id):
		return User.query.get(user_id)
	
	return app

	

webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin') 

@blueprint.route('/')
@admin_required
def admin_index():
	title = "Панель управления"
	return render_template('admin/index.html', page_title=title)
			

webapp/news/views.py
from flask import Blueprint, current_app,render_template

from webapp.news.models import News
from webapp.weather import weather_by_city

blueprint = Blueprint('news', __name__)

@blueprint.route('/')
def index():
	title = 'Новости Python'
	weather_text = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
	news_list = News.query.order_by(News.published.desc()).all()
	return render_template('news/index.html', page_title=title, weather=weather_text, news_list=news_list)

webapp/user/views.py
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user

from webapp import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
	if current_user.is_authenticated:
		return redirect(url_for('news.index'))
	title = 'Авторизация'
	login_form = LoginForm()
	return render_template('user/login.html', page_title=title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter(User.username == form.username.data).first()
		if user and user.check_password(form.password.data):
			login_user(user, remember=form.remember_me.data)
			flash('Вы вошли на сайт')
			return redirect(url_for('news.index'))

	flash('Неправильное имя пользователя или пароль')
	return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
	logout_user()
	flash('Вы успешно разлогинились')
	return redirect(url_for('news.index'))

@blueprint.route('/register')
def register():
	if current_user.is_authenticated:
		return redirect(url_for('news.index'))
	title = 'Регистрация'
	form = RegistrationForm()
	return render_template('user/registration.html', page_title=title, form=form)

@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
	form = RegistrationForm()
	if form.validate_on_submit():
		news_user = User(username=form.username.data, email=form.email.data, role='user')
		news_user.set_password(form.password.data)
		db.session.add(news_user)
		db.session.commit()
		flash('Вы успешно зарегистрировались!')
		return redirect(url_for('user.login'))
	flash('Пожалуйста исправьте ошибки в форме')
	return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include 'menu.html' %}
    <div class="container">
	    <h1>{{ page_title }}</h1>
		{% block content %}{% endblock %}
	</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/login.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container">
    <h1>{{ page_title }}</h1>
	<div class="row">
		<div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}				
				</div>
				{% endif %}
			{% endwith %}
			<form action="{{ url_for('process_login') }}" method="POST">
				{{  form.hidden_tag() }}
				<div class="form-group">
					{{ form.username.label }}
					{{ form.username() }}
				</div>
				<div class="form-group">
					{{ form.password.label }}<br>
					{{ form.password() }}
				</div>
				{{ form.submit() }}
			</form>
		</div>
		<div class="col-8">
			
		</div>
	</div>
	</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Новости Python</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Главная страница </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Искать" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
    </form>
    <ul class="navbar-nav">
      {% if current_user.is_authenticated %}
        <li class="nav-item">        
          <span class="nav-link">Привет, {{ current_user.username }}!</span> 
        </li> 
        {% if current_user.is_admin %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Админка</a>
          </li>
        {% endif %}
        <li class="nav-item">        
          <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
        </li>
        <li class="nav-item">  
          <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
        </li>
      {% endif %}      
    </ul>
  </div>
</nav>

webapp/templates/news/index.html
{% extends "base.html" %}

{% block content %}
	<div class="row">
		<div class="col-8">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}				
				</div>
				{% endif %}
			{% endwith %}
			<h2>Новости</h2>
			{% for news in news_list %}
			<h3><a href="{{ news.url }}">{{ news.title }}</a></h3>
			<p>{{ news.published.strftime('%d.%m.%Y') }}</p>
			<hr />
			{% endfor %}
		</div>
		<div class="col-4">
			<h2>Прогноз погоды</h2>
			{% if weather %}
				Погода: {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}
			{% else %}
				Сервис погоды временно недоступен
			{% endif %}
		</div>
	</div>
{% endblock %}

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %}
	<div class="row">
		<div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}				
				</div>
				{% endif %}
			{% endwith %}
			<form action="{{ url_for('user.process_login') }}" method="POST">
				{{  form.hidden_tag() }}
				<div class="form-group">
					{{ form.username.label }}
					{{ form.username() }}
				</div>
				<div class="form-group">
					{{ form.password.label }}<br>
					{{ form.password() }}
				</div>
				<div class="form-group form-check">
					{{ form.remember_me() }}
					{{ form.remember_me.label(class_='form-check-label') }}
				</div>
				{{ form.submit() }}
			</form>
		</div>
		<div class="col-8">
			
		</div>
	</div>
{% endblock %}

webapp/templates/user/registration.html
{% extends "base.html" %}

{% block content %}
	<div class="row">
		<div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}				
				</div>
				{% endif %}
			{% endwith %}
			<form action="{{ url_for('user.process_reg') }}" method="POST">
				{{  form.hidden_tag() }}
				<div class="form-group">
					{{ form.username.label }}
					{{ form.username() }}
				</div>
				<div class="form-group">
					{{ form.email.label }}
					{{ form.email() }}
				</div>
				<div class="form-group">
					{{ form.password.label }}<br>
					{{ form.password() }}
				</div>
				<div class="form-group">
					{{ form.password2.label }}<br>
					{{ form.password2() }}
				</div>				
				{{ form.submit() }}
			</form>
		</div>
		<div class="col-8">
			
		</div>
	</div>
{% endblock %}